[package]
name = "web"
version = "0.1.0"
edition = "2021"

[dependencies]
dioxus = { workspace = true, features = ["router", "fullstack"] }
dioxus-primitives = { git = "https://github.com/DioxusLabs/components", version = "0.0.1", default-features = false }
shuttle-axum = { version = "0.57.0", optional = true }
shuttle-runtime = { version = "0.57.0", optional = true }
ui = { workspace = true }

[features]
default = []
web = ["dioxus/web"]
server = ["dioxus/server", "ui/server", "dep:shuttle-runtime", "dep:shuttle-axum"]
shuttle-runtime = ["dep:shuttle-runtime"]
shuttle-axum = ["dep:shuttle-axum"]
